### ISSUE TITLE
KeyboardEvent is not defined

### ISSUE THREAD

**Issue by naimis20** [pleerock/ng2-dropdown#10]
Exception: Call to Node module failed with error: ReferenceError: KeyboardEvent is not defined
at C:\Users\nagabe\Work\Angular2\Angular2\Angular2\node_modules\ng2-dropdown\DropdownOpen.js:98:42
at Object.<anonymous> (C:\Users\nagabe\Work\Angular2\Angular2\Angular2\node_modules\ng2-dropdown\DropdownOpen.js:121:2)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Users\nagabe\Work\Angular2\Angular2\Angular2\node_modules\ng2-dropdown\index.js:18:22)

**Comment by matiishyn** [comment]
can be related to #10
